# Generated by Django 5.2.4 on 2025-09-30 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        ('userSkills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='skills.skill'),
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
